import time
import FFX_Xbox
import FFX_Screen
import FFX_Battle
import FFX_menu
import FFX_menuGrid
import FFX_Logs
import FFX_memory

FFXC = FFX_Xbox.FFXC

def BaajEntrance():
    FFX_Screen.awaitMap1()
    print("Starting Baaj exterior area")
    FFXC.set_value('AxisLx', 0)
    FFXC.set_value('AxisLy', 0)
    
    #FFX_memory.closeMenu()
    
    #Now back into the water
    FFXC.set_value('AxisLy', 1)
    time.sleep(1)
    FFXC.set_value('AxisLx', -1)
    time.sleep(0.5)
    FFXC.set_value('AxisLy', 1)
    FFXC.set_value('AxisLx', 0)
    FFX_memory.awaitEvent()
    FFXC.set_value('AxisLx', 0)
    FFXC.set_value('AxisLy', 0)
    time.sleep(0.5)
    print("Dialog between Tidus and Wakka.")
    FFX_memory.clickToControl() #Now should have party.
    
    FFX_Xbox.menuX()
    FFX_Xbox.menuX()
    FFX_Xbox.menuX()
    FFX_Xbox.menuX()
    FFX_Xbox.menuX()
    FFX_Xbox.menuX()
    FFX_Xbox.menuX()
    FFX_Xbox.menuX()
    FFX_Xbox.menuX()
    FFX_Xbox.menuX()
    FFX_Xbox.menuX()
    FFX_Xbox.menuX()
    FFX_Xbox.menuX()
    print("We should now be getting back onto the ramp.")
    FFX_memory.awaitControl()
    
    FFXC.set_value('AxisLy', -1)
    time.sleep(6)
    FFXC.set_value('AxisLy', 0)
    FFXC.set_value('AxisLx', -1)
    time.sleep(0.6)
    print("Near the save sphere.")
    FFXC.set_value('AxisLx', 0)
    time.sleep(0.3)
    FFXC.set_value('AxisLy', -1)
    time.sleep(0.05)
    FFXC.set_value('AxisLy', 0)
    time.sleep(0.3)
    FFX_Xbox.menuB() #Touch
    time.sleep(0.3)
    FFX_Xbox.menuB() #Tutorial screen
    time.sleep(0.5)
    FFX_Xbox.menuDown()
    FFX_Xbox.menuB()
    time.sleep(1)

def sphereGrid():
    FFX_memory.openMenu()
    FFX_Xbox.menuB()
    FFX_Xbox.menuB()
    time.sleep(1)
    
    addUse()
    addZombie()
    addFlee()
    addAgi1()
    addAgi2()
    addAgi3()
    FFX_menuGrid.useShiftLeft('Rikku')
    time.sleep(0.5)
    addAgi4()
    addAgi5()
    
    FFX_menu.awaitQuitSG()
    FFX_memory.closeMenu()

def addUse():
    FFX_menu.awaitUse()
    FFX_Xbox.menuB()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridLeft()
    FFX_menuGrid.gridLeft()
    FFX_menuGrid.gridLeft()
    FFX_menuGrid.gridLeft()
    FFX_menuGrid.gridLeft()
    FFX_menuGrid.gridLeft()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridLeft()
    FFX_menuGrid.gridLeft()
    time.sleep(0.1)
    FFX_Xbox.menuB()

def addZombie():
    FFX_menu.awaitUse()
    FFX_Xbox.menuB()
    FFX_menuGrid.gridRight()
    FFX_menuGrid.gridUp()
    FFX_menuGrid.gridUp()
    FFX_menuGrid.gridUp()
    FFX_menuGrid.gridUp()
    FFX_menuGrid.gridUp()
    FFX_menuGrid.gridUp()
    FFX_menuGrid.gridUp()
    FFX_menuGrid.gridUp()
    time.sleep(0.1)
    FFX_Xbox.menuB()

def addFlee():
    FFX_menu.awaitUse()
    FFX_Xbox.menuB()
    FFX_menuGrid.gridUp()
    FFX_menuGrid.gridLeft()
    FFX_menuGrid.gridLeft()
    time.sleep(0.1)
    FFX_Xbox.menuB()

def addAgi1():
    FFX_menu.awaitUse()
    FFX_Xbox.menuB()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridLeft()
    FFX_menuGrid.gridLeft()
    time.sleep(0.1)
    FFX_Xbox.menuB()

def addAgi2():
    FFX_menu.awaitUse()
    FFX_Xbox.menuB()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridLeft()
    FFX_menuGrid.gridLeft()
    time.sleep(0.1)
    FFX_Xbox.menuB()

def addAgi3():
    FFX_menu.awaitUse()
    FFX_Xbox.menuB()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridLeft()
    FFX_menuGrid.gridLeft()
    FFX_menuGrid.gridLeft()
    FFX_menuGrid.gridLeft()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridLeft()
    FFX_menuGrid.gridLeft()
    FFX_menuGrid.gridLeft()
    time.sleep(0.1)
    FFX_Xbox.menuB()

def addAgi4():
    #Rikku agility
    FFX_menu.awaitUse()
    FFX_Xbox.menuB()
    FFX_menuGrid.gridDown()
    time.sleep(0.1)
    FFX_Xbox.menuB()

def addAgi5():
    FFX_menu.awaitUse()
    FFX_Xbox.menuB()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridDown()
    FFX_menuGrid.gridLeft()
    time.sleep(0.1)
    FFX_Xbox.menuB()

def items():
    FFX_memory.closeMenu()
    FFXC.set_value('AxisLy', -1)
    time.sleep(1)
    FFX_memory.awaitEvent()
    FFXC.set_value('AxisLy', 0)
    time.sleep(0.2)
    FFX_memory.awaitControl()
    
    #Rin's screen
    FFXC.set_value('AxisLy', -1)
    FFXC.set_value('AxisLx', 1)
    time.sleep(1)
    FFXC.set_value('AxisLx', 0)
    FFX_memory.clickToEvent()
    FFXC.set_value('AxisLy', 0)
    time.sleep(2.5)
    FFX_Xbox.menuB()
    time.sleep(0.7)
    FFX_Xbox.menuDown()
    FFX_Xbox.menuB() #Got any items?
    time.sleep(1.2)
    FFX_Xbox.menuB() #Buy
    time.sleep(0.15)
    for x in range(9):
        FFX_Xbox.menuB()
        time.sleep(0.15)
        FFX_Xbox.menuB()
        if x < 8:
            time.sleep(0.15)
            FFX_Xbox.menuDown()
    FFX_memory.closeMenu()
    FFX_memory.itemHack(2)
    
    #Now ready for the weapons and armor we're going to use.
    while not FFX_memory.menuOpen():
        FFX_Xbox.menuB()
    
    time.sleep(0.2)
    FFX_Xbox.menuB() #Buy
    time.sleep(0.3)
    FFX_Xbox.menuB()
    time.sleep(0.3)
    FFX_Xbox.menuUp()
    FFX_Xbox.menuB()
    time.sleep(0.1)
    FFX_Xbox.menuUp()
    FFX_Xbox.menuB() #Buy and equip Tidus weapon
    time.sleep(0.1)
    FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    FFX_Xbox.menuB()
    time.sleep(0.1)
    FFX_Xbox.menuUp()
    FFX_Xbox.menuB()
    time.sleep(0.1)
    FFX_Xbox.menuUp()
    FFX_Xbox.menuB() #Buy and equip Auron weapon
    time.sleep(0.1)
    FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    FFX_Xbox.menuB()
    time.sleep(0.1)
    FFX_Xbox.menuUp()
    FFX_Xbox.menuB()
    time.sleep(0.1)
    FFX_Xbox.menuUp()
    FFX_Xbox.menuB() #Buy and equip Tidus armor
    time.sleep(0.1)
    
    FFX_memory.closeMenu()
    time.sleep(1.4)
    FFX_Xbox.menuB()
    FFX_memory.awaitControl()
    FFX_memory.openMenu()
    FFX_Xbox.menuUp()
    FFX_Xbox.menuUp()
    FFX_Xbox.menuUp()
    FFX_Xbox.menuB()
    time.sleep(0.6)
    FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    time.sleep(0.1)
    FFX_Xbox.menuB() #Customize Tidus weapon
    time.sleep(0.2)
    FFX_Xbox.menuB()
    time.sleep(0.1)
    FFX_Xbox.menuUp()
    FFX_Xbox.menuB() #First Strike
    time.sleep(0.1)
    FFX_Xbox.menuA()
    FFX_Xbox.menuA()
    FFX_Xbox.menuDown()
    time.sleep(0.1)
    FFX_Xbox.menuB() #Customize Auron weapon
    time.sleep(0.2)
    FFX_Xbox.menuB()
    time.sleep(0.1)
    FFX_Xbox.menuUp()
    FFX_Xbox.menuB() #First Strike
    time.sleep(0.1)
    FFX_Xbox.menuA()
    FFX_Xbox.menuA()
    FFX_Xbox.menuDown()
    time.sleep(0.1)
    FFX_Xbox.menuB() #Tidus armor
    time.sleep(0.3)
    #FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    FFX_Xbox.menuB()
    time.sleep(0.1)
    FFX_Xbox.menuUp()
    FFX_Xbox.menuB() #Auto-Haste
    time.sleep(0.1)
    FFX_Xbox.menuA()
    FFX_Xbox.menuDown()
    time.sleep(0.1)
    FFX_Xbox.menuB()
    time.sleep(0.1)
    FFX_Xbox.menuUp()
    FFX_Xbox.menuB() #No Encounters
    time.sleep(0.1)
    
    #Need more chocobo wings.
    FFX_memory.closeMenu()
    FFX_memory.itemHack(2)
    time.sleep(0.1)
    FFX_memory.openMenu()
    
    FFX_Xbox.menuUp()
    FFX_Xbox.menuUp()
    FFX_Xbox.menuUp()
    FFX_Xbox.menuB()
    time.sleep(0.6)
    FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    time.sleep(0.1)
    FFX_Xbox.menuB() #Rikku armor
    FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    FFX_Xbox.menuDown()
    FFX_Xbox.menuB() #Auto-haste
    time.sleep(0.1)
    FFX_Xbox.menuUp()
    FFX_Xbox.menuB() #Auto-Haste
    time.sleep(0.1)
    FFX_memory.closeMenu()
    
    FFXC.set_value('AxisLy', 1)
    time.sleep(0.3)
    FFXC.set_value('AxisLx', -1)
    FFX_memory.awaitEvent()
    FFXC.set_value('AxisLx', 0)
    FFXC.set_value('AxisLy', 0)
    time.sleep(0.2)

def BackToSin():
    FFX_memory.awaitControl()
    print("Ready to go.")
    
    #Ready to finish the game.
    FFXC.set_value('AxisLy', 1)
    time.sleep(2.8)
    FFXC.set_value('AxisLx', -1)
    time.sleep(0.25)
    FFX_memory.clickToEvent()
    FFXC.set_value('AxisLy', 0)
    FFXC.set_value('AxisLx', 0)
    
    time.sleep(0.2)
    FFX_Xbox.SkipDialog(5.7)
    FFX_Xbox.skipScene()
    #FFX_memory.awaitControl()
    print("Ready for Inside Sin pathing")